urls.py
from django.contrib import admin
from django.urls import path
from transactions import views
#from django.contrib.auth import views as auth_views

app_name = 'transactions'
urlpatterns = [
    path('', views.index, name='index'),
    path('summary/', views.financial_summary, name='financial_summary'),
    path('register_income/', views.income_registration, name='income_registration'),
    path('register_expense/', views.expense_registration, name='expense_registration'),
    path('bank/<int:pk>/', views.bank_detail, name='bank_detail'), 
    path('add_bank/', views.add_bank, name='add_bank'), 
    path('cash/<int:pk>/', views.cash_detail, name='cash_detail'), 
    path('add_cash_amount/', views.add_cash_amount, name='add_cash_amount'), 
    path('create_recurring_transaction/', views.create_recurring_transaction, name='recurring_transaction'),
    
    path('portfolio_details/<int:pk>/', views.portfolio_details, name="portfolio_details"),
    path('manage_stock/<int:pk>/', views.manage_stock, name='manage_stock'),
    path('create_portfolio/', views.create_portfolio, name="create_portfolio"),
    path('eliminate_portfolio/<int:pk>/', views.eliminate_portfolio, name="eliminate_portfolio"),
    path('portfolio/<int:pk>/manage_cash/', views.manage_cash, name='manage_cash'),


    #add the next two on main url file
    #path('login/', auth_views.LoginView.as_view(), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

templates/transactions/bank_detail.html
{% extends "website/base.html" %}

{% block title %}Bank Account Detail{% endblock %}

{% block content %}
<style>

  /* Stile personalizzato per il colore arancione del bottone */
  .btn-custom {
      color: #000; /* Testo nero */
      background-color: #FFD180; /* Colore arancione personalizzato */
      border-color: #FFD180; /* Colore del bordo */
  }
  
</style>
  
<div id="notification-container" class="position-fixed top-0 end-0 p-3" style="z-index: 5">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
</div>



<div class="container mt-5">  
  <div class="d-flex flex-row-reverse m-1">
    <a href="{% url 'transactions:index' %}" class="btn btn-custom">Back to Main Page</a>
  </div>
  <div class="card">
      <div class="card-body">
          <h5 class="card-title">{{ bank_account.name }}</h5>
          <p class="card-text">
            Balance: <span id="bank-balance-{{ bank_account.pk }}">{{ bank_account.balance }}</span>
          </p>
      </div>
  </div>

  <div class="col-12">
    {{ html_fig | safe }}
  </div>

      <div class="row mt-4 p-2">
        <div class="col-md-6 mb-4 p-2">
          <form method="post" id="transferForm" target="_self">
            <h4>Transfer Funds</h4>
            {% csrf_token %}
            <div class="mb-3">
                <label for="target_account" class="form-label">Target Account:</label>
                <select class="form-select" id="target_account" name="target_account" required>
                    {% for bank_account in bank_accounts %}
                        <option value="{{ bank_account.name }}">{{ bank_account.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="amount" class="form-label">Amount:</label>
                <input type="number" class="form-control" id="amount" name="amount" required>
            </div>
            <div class="mb-3">
                <label for="commission" class="form-label">Commission:</label>
                <input type="number" class="form-control" id="commission" name="commission" required>
            </div>
            <button type="submit" class="btn btn-custom" name="transfer_button">Transfer</button>
          </form>
        </div>
        <div class="col-md-6 p-2">
          <form method="post" id="retireForm" target="_self">
            <h4>Retire Funds</h4>
            {% csrf_token %}
            <div class="mb-3">
                <label for="target_account" class="form-label">Target Cash Amount:</label>
                <select class="form-select" id="target_account" name="target_account" required>
                    {% for cash_amount in cash_amounts %}
                        <option value="{{ cash_amount.id }}">{{ cash_amount }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="retire_amount" class="form-label">Amount:</label>
                <input type="number" class="form-control" id="retire_amount" name="retire_amount" required>
            </div>
            <div class="mb-3">
                <label for="retire_commission" class="form-label">Commission:</label>
                <input type="number" class="form-control" id="retire_commission" name="retire_commission" required>
            </div>
            <button type="submit" class="btn btn-custom" name="retire_button">Retire</button>
          </form>
        </div>
      </div>

      
    </div>
  </div>
</div>

{% endblock %}

templates/transactions/cash_detail.html
{% extends "website/base.html" %}

{% block title %}Cash Account Detail{% endblock %}


{% block content %}
<style>

  /* Stile personalizzato per il colore arancione del bottone */
  .btn-custom {
      color: #000; /* Testo nero */
      background-color: #FFD180; /* Colore arancione personalizzato */
      border-color: #FFD180; /* Colore del bordo */
  }
  
</style>
  
<div id="notification-container" class="position-fixed top-0 end-0 p-3" style="z-index: 5">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
</div>

<div class="container mt-5 px-2 d-flex justify-content-center flex-column">
  <div class="d-flex flex-row-reverse m-1">
    <a href="{% url 'transactions:index' %}" class="btn btn-custom">Back to Main Page</a>
  </div>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Cash</h5>
      <p class="card-text">Amount: {{ cash_account.amount }}</p>      
    </div>
  </div>
  


  <div class="col-12">  
    {{ html_fig | safe }}
  </div>
  
  
  <div class="col-md-6 p-2 mt-4">
    <h2>Cash deposit </h2>
    <form method="post" class="justify-content-center" >
      {% csrf_token %}
      <div class="mb-3">
        {{ deposit_form.amount.label_tag }} 
        {{ deposit_form.amount }}
      </div>
      <div class="mb-3">
        {{ deposit_form.bank_account.label_tag }} 
        {{ deposit_form.bank_account }}
      </div>
      <button type="submit" class="btn btn-custom">Deposit</button>
    </form>
  </div>

</div>

{% endblock %}

templates/transactions/create_portfolio.html
<!-- create_portfolio.html -->

{% extends 'website/base.html' %}

{% block content %}
  <h2 class="text-center">Create new Portfolio</h2>

  <form method="post" class="container mx-auto col-6 ">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Name:</label>
      <input type="text" class="form-control" id="name" name="name" required>
    </div>
    <div class="form-group">
      <label for="start_date">Start Date:</label>
      <input type="date" class="form-control" id="start_date" name="start_date" required>
    </div>
    <div class="form-group">
      <label for="name">Cash balance:</label>
      <input type="number" class="form-control" id="cash_balance" name="cash_balance" value="0" required>
    </div>
    <button type="submit" class="btn btn-primary m-2">Create Portfolio</button>
  </form>

  <script>
    document.getElementById('start_date').valueAsDate = new Date();
  </script>
{% endblock %}

templates/transactions/form.html
{% extends "website/base.html" %}

{% block title %}Form{% endblock %}

{% block content %}
<style>
/* Stilizza le spese urgenti in rosso */
.list-group-item-danger {
  background-color: #f8d7da;
  color: #721c24;
}

</style>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form action="{% url 'transactions:financial_summary' %}" method="POST" class="mt-5 row">
        {% csrf_token %}
        <div class="col-md-6 mb-3">
          <label for="startDate" class="form-label text-primary">Start Date</label>
          <input type="date" class="form-control" name="startDate" id="startDate" aria-describedby="dateHelp">
          <div id="dateHelp" class="form-text">Enter the starting date of the transactions</div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="endDate" class="form-label text-primary">End Date</label>
          <input type="date" class="form-control" name="endDate" id="endDate" aria-describedby="dateHelp">
          <div id="dateHelp" class="form-text">Enter the ending date of the transactions</div>
        </div>
        <button type="submit" class="col-12 btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div>

{% if future_expenses %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="text-center mb-4">Future Expenses</h2>
      <ul class="list-group">
        {% for future_expense in future_expenses %}
          <li class="list-group-item {% if future_expense.is_urgent %}list-group-item-danger{% endif %}">
            {{ future_expense.amount }} - {{ future_expense.description }} - {{ future_expense.date }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endif %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <h2 class="text-center mb-4">Bank Accounts & Cash</h2>
      <div class="card" style="width: 12rem;">
        <div class="card-body">
          <h5 class="card-title">Cash</h5>
          <p class="card-text">Amount: {{ cash.amount }}</p>
          <a href="{% url 'transactions:cash_detail' pk=cash.pk %}" class="btn btn-primary">Go to Cash</a>
        </div>
      </div>
      {% for bank_account in bank_accounts %}
      <div class="card" style="width: 12rem;">
        <div class="card-body">
          <h5 class="card-title">{{ bank_account.bank_name }}</h5>
          <p class="card-text">Balance: {{ bank_account.balance }}</p>
          <a href="{% url 'transactions:bank_detail' pk=bank_account.pk %}" class="btn btn-primary">Go to Bank Account</a>
        </div>
      </div>
      {% endfor %}
      <div class="card mt-4">
        <div class="card-body">
          <h5 class="card-title">Total Savings</h5>
          <p class="card-text">Amount: {{ total_savings }}</p>
        </div>
      </div>

  </div>
</div>


<script>
  // Ottieni l'elemento "Start Date"
  const startDateInput = document.getElementById('startDate');
  
  // Ottieni l'elemento "End Date"
  const endDateInput = document.getElementById('endDate');

  // Crea una data per l'inizio dell'anno corrente
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  const firstDayOfYear = new Date(currentYear, 0, 1);

  // Imposta il valore dell'input "Start Date" con la data di inizio anno
  startDateInput.valueAsDate = firstDayOfYear;

  // Imposta il valore dell'input "End Date" con la data odierna
  endDateInput.valueAsDate = currentDate;
</script>

{% endblock %}

templates/transactions/overview.html
{% extends "website/base.html" %}

{% block title %}Overview{% endblock %}

{% block content %}
<style>
/* Stilizza le spese urgenti in rosso */
.list-group-item-danger {
  background-color: #f8d7da;
  color: #721c24;
}
/* Stile personalizzato per il colore arancione del bottone */
.btn-custom {
    color: #000; /* Testo nero */
    background-color: #FFD180; /* Colore arancione personalizzato */
    border-color: #FFD180; /* Colore del bordo */
}


</style>


<div class="container py-3 d-flex justify-content-center">
  <div class="row justify-content-center col-lg-8">
      <form action="{% url 'transactions:financial_summary' %}" method="POST" class="mt-5 row g-3">
          {% csrf_token %}
          <div class="col-md-6">
              <label for="startDate" class="form-label text">Start Date</label>
              <div class="input-group">
                  <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                  <input type="date" class="form-control" name="startDate" id="startDate" aria-describedby="dateHelp">
              </div>
              <div id="dateHelp" class="form-text">Enter the starting date of the transactions</div>
          </div>
          <div class="col-md-6">
              <label for="endDate" class="form-label text">End Date</label>
              <div class="input-group">
                  <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                  <input type="date" class="form-control" name="endDate" id="endDate" aria-describedby="dateHelp">
              </div>
              <div id="dateHelp" class="form-text">Enter the ending date of the transactions</div>
          </div>
          <div class="col-12">
              <button type="submit" class="btn btn-custom col-12">Submit</button>
          </div>
      </form>
  </div>
</div>



{% if future_expenses %}
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="text-center mb-4">Future Expenses</h2>
      <ul class="list-group">
        {% for future_expense in future_expenses %}
          <li class=" mt-1 list-group-item {% if future_expense.is_urgent %}list-group-item-danger{% endif %}">
            {{ future_expense.amount }} - {{ future_expense.description }} - {{ future_expense.date }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endif %}

<div class="container mt-5">
  <div class="row justify-content-center">
    <h2 class="text-center mb-4">Bank Accounts & Cash & Portfolios</h2>
    {% for cash in cash_amounts %}
      <div class="card m-1" style="width: 12rem;">
        <div class="card-body">
          <h5 class="card-title">Cash</h5>
          <p class="card-text">Amount: {{ cash.amount }}</p>
          <a href="{% url 'transactions:cash_detail' pk=cash.pk %}" class="btn btn-custom">Check Cash Amount</a>
        </div>
      </div>
      {% endfor %}
      {% for bank_account in bank_accounts %}
      <div class="card" style="width: 12rem;">
        <div class="card-body">
          <h5 class="card-title">{{ bank_account.name }}</h5>
          <p class="card-text">Balance: {{ bank_account.balance }}</p>
          <a href="{% url 'transactions:bank_detail' pk=bank_account.pk %}" class="btn btn-custom">Check Account</a>
        </div>
      </div>
      {% endfor %}
      {% for portfolio in portfolios %}
      <div class="card" style="width: 12rem;">
        <div class="card-body">
          <h5 class="card-title">{{ portfolio.name }}</h5>
          <p class="card-text">Balance: {{ portfolio.total_value }}</p>
          <a href="{% url 'transactions:portfolio_details' pk=portfolio.pk %}" class="btn btn-custom">Check Portfolio</a>
        </div>
      </div>
      {% endfor %}

      <div class="card m-4 col-10">
        <div class="card-body">
          <h5 class="card-title">Total Savings</h5>
          <p class="card-text">Amount: {{ total_savings }}</p>
        </div>
      </div>

  </div>

  <!-- Button per aprire il form per creare un account di banca-->
  <div class="d-flex justify-content-center mx-auto align-items-center flex-column">    
    <a class="btn btn-custom col-6 text-center" type="button" data-bs-toggle="collapse" data-bs-target="#addBankAccount" aria-expanded="false" aria-controls="addBankAccount"> add Bank Account</a>
            
    <div class="col-md-4 mx-auto collapse"  id="addBankAccount">
        <!-- Form for Income Registration -->
        <h5> Add Bank Account </h5>
        <form method="post" action="{% url 'transactions:add_bank' %}" class="m-3">
            {% csrf_token %}
            {{ add_bank_form.as_p }}
            <div class="text-center">
                <button type="submit" class="btn btn-custom">Create new Bank account</button>
            </div>
        </form>
    </div>
    <a class="btn btn-custom col-6 text-center" type="button" data-bs-toggle="collapse" data-bs-target="#addCashAmount" aria-expanded="false" aria-controls="addCashAmount"> add Cash Amount</a>
    <div class="col-md-4 mx-auto collapse"  id="addCashAmount">
        <!-- Form for Income Registration -->
        <h5> Add Cash Amount </h5>
        <form method="post" action="{% url 'transactions:add_cash_amount' %}" class="m-3">
            {% csrf_token %}
            {{ add_cash_form.as_p }}
            <div class="text-center">
                <button type="submit" class="btn btn-custom">Create new Cash Amount</button>
            </div>
        </form>
    </div>
    <a class="btn btn-custom col-6 text-center" type="button" data-bs-toggle="collapse" data-bs-target="#addPortfolio" aria-expanded="false" aria-controls="addPortfolio"> add Portfolio</a>
    <div class="col-md-4 mx-auto collapse"  id="addPortfolio">
        <!-- Form for Income Registration -->
        <h5> Add portfolio </h5>
        <form method="post" action="{% url 'transactions:create_portfolio' %}" class="m-3">
            {% csrf_token %}
            {{ add_bank_form.as_p }}
            <div class="text-center">
                <button type="submit" class="btn btn-custom">Create new Portfolio</button>
            </div>
        </form>
    </div>


  </div>
</div>


<script>
  // Ottieni l'elemento "Start Date"
  const startDateInput = document.getElementById('startDate');
  
  // Ottieni l'elemento "End Date"
  const endDateInput = document.getElementById('endDate');

  // Crea una data per l'inizio dell'anno corrente
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  const firstDayOfYear = new Date(currentYear, 0, 1);

  // Imposta il valore dell'input "Start Date" con la data di inizio anno
  startDateInput.valueAsDate = firstDayOfYear;

  // Imposta il valore dell'input "End Date" con la data odierna
  endDateInput.valueAsDate = currentDate;
</script>

{% endblock %}

templates/transactions/portfolio.html
{% extends "website/base.html" %}
{% load static %}

{% block content %} 
<style>

    /* Stile personalizzato per il colore arancione del bottone */
    .btn-custom {
        color: #000; /* Testo nero */
        background-color: #FFD180; /* Colore arancione personalizzato */
        border-color: #FFD180; /* Colore del bordo */
    }
    
  </style>
<div class="container">
    <div class="d-flex flex-column flex-sm-row justify-content-around">
        <h1 class="mt-4 text-center">Portfolio Dashboard</h1>
        <a class="btn btn-danger mt-5 mb-1" href="{% url 'transactions:eliminate_portfolio' portfolio.pk %}">Eliminate</a>
    </div>
    <!-- Visualizza le caratteristiche del portfolio -->
    <h2 class="mt-4">Portfolio Details</h2>
    <div class="row">
        <div class="col">
            <p>Total Value: ${{ portfolio.total_value }}</p>
            <p>Stock Value: ${{ portfolio.stock_value }}</p>
            <p>Cash Balance: ${{ portfolio.cash_balance }}</p>
            <p>ROI: {{ portfolio.calculate_roi }}%</p>
        </div>
    </div>
    
    <!-- Mostra la lista delle azioni presenti nel portfolio -->
    <h2 class="mt-4">Stocks in Portfolio</h2>
    <div class="row">
        <div class="col">
            <ul class="list-group">
                {% for stock in portfolio.stocks.all %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <h5 class="mb-0">{{ stock.company.name }}</h5>
                                <p class="mb-0">Quantity: {{ stock.quantity }}</p>
                                <p class="mb-0">Price: {{ stock.price }}</p>
                            </div>
                        </div>
                    </li>
                {% empty %}
                    <li class="list-group-item">
                        <p class="mt-2 mb-0">No stocks available in the portfolio.</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
    <!-- Aggiungi una nuova azione al portfolio -->
    <h2 class="mt-4">Manage portfolio</h2>
    <div class="row">
        <div class="col">
            <form method="POST" action="{% url 'transactions:manage_stock' pk=portfolio.pk %}">
                {% csrf_token %}
                {{ form_stocks.as_p }}
                <button type="submit" class="btn btn-custom">Esegui</button>
            </form>
        </div>
    </div>

    <div class="container">
        <h1 class="mt-4 text-center">Manage Cash</h1>
        <div class="row">
            <div class="col">
                <form method="POST" action="{% url 'transactions:manage_cash' pk=portfolio.pk %}">
                    {% csrf_token %}
                    {{ form_cash.as_p }}
                    <button type="submit" class="btn btn-custom">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="notification-container" class="position-fixed top-0 end-0 p-3" style="z-index: 5">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
</div>

   
{% endblock %}

templates/transactions/recurring_transaction.html
{% extends "website/base.html" %}

{% block title %}Create Recurring Transaction{% endblock %}

{% block content %}
<style>

  /* Stile personalizzato per il colore arancione del bottone */
  .btn-custom {
      color: #000; /* Testo nero */
      background-color: #FFD180; /* Colore arancione personalizzato */
      border-color: #FFD180; /* Colore del bordo */
  }
  
</style>
<div class="container mt-5">
  <div class="row justify-content-center">
   
  </div>
</div>

<div class="fixed-bottom fixed-start p-3">
  <a href="{% url 'transactions:index' %}" class="btn btn-custom">Back to Main Page</a>
</div>




{% endblock %}